#!/bin/sh
gfortran -fdefault-real-8 -std=f95 -c tools.f90
gfortran -fdefault-real-8 -std=f95 -c diffusion.f90
gfortran -fdefault-real-8 -std=f95 -c testing.f90
gfortran -fdefault-real-8 -std=f95 -c main.f90
gfortran -fdefault-real-8 -std=f95 -o pro2 main.o testing.o diffusion.o tools.o
